In [27]:
import numpy as np
from numpy.random import default_rng

In [7]:
# array creation
arr = np.array([22, 33, 44, 55], dtype=np.int32)
arr

array([22, 33, 44, 55], dtype=int32)

In [5]:
# number of dimensions
arr.ndim

1

In [8]:
# array shape
arr.shape

(4,)

In [9]:
# array data type
arr.dtype

dtype('int32')

In [10]:
# array size
arr.size

4

In [13]:
# reshape (4) can be splited to rows and columns representing the array size
arr = arr.reshape(2, 2)
arr

array([[22, 33],
       [44, 55]], dtype=int32)

In [14]:
arr.size

4

In [15]:
arr.shape

(2, 2)

In [17]:
# flat the array
arr.flatten()

array([22, 33, 44, 55], dtype=int32)

In [19]:
arr

array([[22, 33],
       [44, 55]], dtype=int32)

In [20]:
# indexing and slicing
arr[0]

array([22, 33], dtype=int32)

In [22]:
arr[0, 0]

22

In [24]:
arr[0, -1]

33

In [25]:
arr = arr.reshape(4, 1)
arr

array([[22],
       [33],
       [44],
       [55]], dtype=int32)

In [26]:
arr[1:3, :]

array([[33],
       [44]], dtype=int32)

In [34]:
rnd = default_rng(123)
random_array = rnd.integers(10, 20, size=20)
random_array

array([10, 16, 15, 10, 19, 12, 12, 11, 13, 11, 13, 18, 14, 19, 14, 12, 17,
       18, 18, 18])

In [37]:
np.zeros((3,),dtype=np.int32)

array([0, 0, 0], dtype=int32)

In [39]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [42]:
random_array[random_array > 13]

array([16, 15, 19, 18, 14, 19, 14, 17, 18, 18, 18])

In [43]:
random_array[(random_array > 13) & (random_array % 2 ==0)]

array([16, 18, 14, 14, 18, 18, 18])

In [45]:
random_array[(random_array > 13) | (random_array == 11)] 

array([16, 15, 19, 11, 11, 18, 14, 19, 14, 17, 18, 18, 18])

In [46]:
random_array * 100

array([1000, 1600, 1500, 1000, 1900, 1200, 1200, 1100, 1300, 1100, 1300,
       1800, 1400, 1900, 1400, 1200, 1700, 1800, 1800, 1800])

In [47]:
random_array / 2

array([5. , 8. , 7.5, 5. , 9.5, 6. , 6. , 5.5, 6.5, 5.5, 6.5, 9. , 7. ,
       9.5, 7. , 6. , 8.5, 9. , 9. , 9. ])

In [89]:
np.concatenate((random_array, random_array))

array([10, 16, 15, 10, 19, 12, 12, 11, 13, 11, 13, 18, 14, 19, 14, 12, 17,
       18, 18, 18, 10, 16, 15, 10, 19, 12, 12, 11, 13, 11, 13, 18, 14, 19,
       14, 12, 17, 18, 18, 18])

In [51]:
arr1 = np.arange(0, 5, 1)
arr1

array([0, 1, 2, 3, 4])

In [52]:
arr2 = np.array(["enosh", "tomer", "matanel", "alef", "itshak"])
arr2

array(['enosh', 'tomer', 'matanel', 'alef', 'itshak'], dtype='<U7')

In [54]:
arr2[arr1 %  2 == 0]

array(['enosh', 'matanel', 'itshak'], dtype='<U7')

In [65]:
np.where(arr1 % 2 == 0, "koko", "jumbo")

array(['koko', 'jumbo', 'koko', 'jumbo', 'koko'], dtype='<U5')

In [69]:
random_array.min()

10

In [70]:
random_array.max()

19

In [71]:
random_array.sum()

290

In [72]:
random_array.mean()

14.5

In [76]:
arr2d = random_array.reshape(5, 4)
arr2d

array([[10, 16, 15, 10],
       [19, 12, 12, 11],
       [13, 11, 13, 18],
       [14, 19, 14, 12],
       [17, 18, 18, 18]])

In [77]:
arr2d.min(axis=0)

array([10, 11, 12, 10])

In [78]:
arr2d.min(axis=1)

array([10, 11, 11, 12, 17])

In [79]:
arr2d.sum(axis=0)

array([73, 76, 72, 69])

In [80]:
arr2d.sum(axis=1)

array([51, 54, 55, 59, 71])

In [82]:
random_array

array([10, 16, 15, 10, 19, 12, 12, 11, 13, 11, 13, 18, 14, 19, 14, 12, 17,
       18, 18, 18])

In [83]:
np.unique(random_array)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [84]:
np.sort(random_array)

array([10, 10, 11, 11, 12, 12, 12, 13, 13, 14, 14, 15, 16, 17, 18, 18, 18,
       18, 19, 19])

In [85]:
np.vectorize(lambda n: n * 2 if n % 2 == 0 else n * 10)(random_array)

array([ 20,  32, 150,  20, 190,  24,  24, 110, 130, 110, 130,  36,  28,
       190,  28,  24, 170,  36,  36,  36])

In [86]:
np.array([x + 90 if x < 13 else x + 1000 for x in random_array])

array([ 100, 1016, 1015,  100, 1019,  102,  102,  101, 1013,  101, 1013,
       1018, 1014, 1019, 1014,  102, 1017, 1018, 1018, 1018])

In [87]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])
arr2d + arr1d

array([[11, 22, 33],
       [14, 25, 36]])

In [88]:
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([10, 20, 30, 40])  # Shape (1, 4)
arr1 + arr2

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

In [90]:
arr1 = [1, 2, 3]
arr2 = [4, 5, 6]
np.vstack((arr1, arr2))


array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [93]:
random_array

array([10, 16, 15, 10, 19, 12, 12, 11, 13, 11, 13, 18, 14, 19, 14, 12, 17,
       18, 18, 18])

In [94]:
random_array.argmax()

4

In [95]:
random_array.argmin()

0

In [99]:
np.intersect1d(random_array, np.array([[3, 10], [18, 90]]).flatten())

array([10, 18])

In [101]:
np.isin(random_array, [10, 3, 18])

array([ True, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
        True,  True])

In [102]:
x = random_array[np.isin(random_array, np.arange(0, 15))]
x

array([10, 10, 12, 12, 11, 13, 11, 13, 14, 14, 12])

In [103]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
arr1, arr2 = np.split(arr2d, 2)
arr1

array([[1, 2, 3]])

In [107]:
arr2

array([[4, 5, 6]])

In [108]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.roll(arr2d, shift=2, axis=1)

array([[2, 3, 1],
       [5, 6, 4]])

In [112]:
np.roll(arr2d, shift=1, axis=0)

array([[4, 5, 6],
       [1, 2, 3]])