In [1]:
import numpy as np
from numpy.random import default_rng

In [6]:
rng = default_rng(42)
random_arr = rng.integers(1, 100, size=20)
random_arr

array([ 9, 77, 65, 44, 43, 86,  9, 70, 20, 10, 53, 97, 73, 76, 72, 78, 51,
       13, 84, 45])

In [8]:
float_arr = rng.random(15)
float_arr

array([0.19463871, 0.466721  , 0.04380377, 0.15428949, 0.68304895,
       0.74476216, 0.96750973, 0.32582536, 0.37045971, 0.46955581,
       0.18947136, 0.12992151, 0.47570493, 0.22690935, 0.66981399])

In [9]:
arr1d = np.arange(1, 11)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
nested_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
nested_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [12]:
names_arr = np.array(['Matanel', 'Alef', 'Omer', 'Itshak', 'Maor', 'Elly', 'Tomer', 'Yossi'])
names_arr

array(['Matanel', 'Alef', 'Omer', 'Itshak', 'Maor', 'Elly', 'Tomer',
       'Yossi'], dtype='<U7')

In [13]:
# Exercise 1: Array Reshaping
"""
Reshape random_arr into a 4x5 array
Your code here:
"""

'\nReshape random_arr into a 4x5 array\nYour code here:\n'

In [14]:
# Exercise 2: Array Flattening
"""
Flatten nested_arr into a 1D array
Your code here:
"""


'\nFlatten nested_arr into a 1D array\nYour code here:\n'

In [19]:
# Exercise 3: Array Concatenation
"""
Concatenate arr1d with itself horizontally
Your code here:
"""

'\nConcatenate arr1d with itself horizontally\nYour code here:\n'

In [20]:
# Exercise 4: Basic Slicing
"""
Get every second element from arr1d
Your code here:
"""

'\nGet every second element from arr1d\nYour code here:\n'

In [21]:
# Exercise 5: Advanced Slicing
"""
Get the middle 2x2 subarray [[4, 5], [7, 8]] from nested_arr
Your code here:
"""

'\nGet the middle 2x2 subarray [[4, 5], [7, 8]] from nested_arr\nYour code here:\n'

In [27]:
# Exercise 6: Reverse Indexing
"""
Reverse the order of elements in arr1d
Your code here:
"""

'\nReverse the order of elements in arr1d\nYour code here:\n'

In [29]:
# Exercise 7: Simple Filtering
"""
Get all elements from random_arr that are greater than 50
Your code here:
"""

'\nGet all elements from random_arr that are greater than 50\nYour code here:\n'

In [30]:
# Exercise 8: Multiple Conditions
"""
Get elements from random_arr that are both even and greater than 30
Your code here:
"""

'\nGet elements from random_arr that are both even and greater than 30\nYour code here:\n'

In [31]:
# Exercise 9: String Filtering
"""
Get all names from names_arr that start with the letter 'A' or 'M'
Your code here:
"""

"\nGet all names from names_arr that start with the letter 'A' or 'M'\nYour code here:\n"

In [32]:
# Exercise 10: Basic Vectorization
"""
Multiply each element in arr1d by its index position + 1
Your code here:
"""

'\nMultiply each element in arr1d by its index position + 1\nYour code here:\n'

In [33]:
# Exercise 11: Custom Function Vectorization
"""
Create a vectorized function that replaces numbers less than 5 with 0 
and numbers greater than 5 with 10 in arr1d
Your code here:
"""

'\nCreate a vectorized function that replaces numbers less than 5 with 0 \nand numbers greater than 5 with 10 in arr1d\nYour code here:\n'

In [34]:
# Exercise 12: String Vectorization
"""
Add the suffix '_user' to each name in names_arr
Your code here:
"""


"\nAdd the suffix '_user' to each name in names_arr\nYour code here:\n"

In [35]:
# Exercise 13: Simple Broadcasting
"""
Add [1, 2, 3, 4] to each row of arr2d
Your code here:
"""

'\nAdd [1, 2, 3, 4] to each row of arr2d\nYour code here:\n'

In [36]:
# Exercise 14: Array Comparisons
"""
Find elements that appear in both arr1d and nested_arr.flatten()
Your code here:
"""

'\nMultiply each column in nested_arr by [1, 2, 3, 4] (one multiplier per row)\nYour code here:\n'

In [37]:
# Exercise 15: Normalization
"""
Normalize random_arr to be between 0 and 1
Your code here:
"""

'\nNormalize random_arr to be between 0 and 1\nYour code here:\n'

In [38]:
# Exercise 16: Array Splitting
"""
Split arr2d horizontally into 2 equal arrays
Your code here:
"""

'\nSplit arr2d horizontally into 2 equal arrays\nYour code here:\n'

In [39]:
# Exercise 17: Array Stacking
"""
Stack arr1d three times vertically
Your code here:
"""

'\nStack arr1d three times vertically\nYour code here:\n'

In [40]:
# Exercise 18: Array Rolling
"""
Roll nested_arr by 2 positions along axis 1
Your code here:
"""

'\nRoll nested_arr by 2 positions along axis 1\nYour code here:\n'

In [41]:
# Exercise 19: Simple Where
"""
Replace all even numbers in arr1d with -1 using np.where
Your code here:
"""


'\nReplace all even numbers in arr1d with -1 using np.where\nYour code here:\n'

In [42]:
# Exercise 20: Multiple Conditions
"""
Create an array same shape as random_arr with:
'low' for values < 30
'medium' for values between 30 and 70
'high' for values > 70
Your code here:
"""

"\nCreate an array same shape as random_arr with:\n'low' for values < 30\n'medium' for values between 30 and 70\n'high' for values > 70\nYour code here:\n"

In [43]:
# Exercise 21: Maximum roll
"""
Roll nested_arr by 2 positions along axis 1
Calculate the maximum value in axis 1
Your code here:
"""


'\nRoll nested_arr by 2 positions along axis 1\nCalculate the maximum value in axis 1\nYour code here:\n'

In [44]:
# Exercise 22: Mean
"""
Find the mean of nested_arr in axis 1
Your code here:
"""

'\nFind the mean of nested_arr in axis 1\nYour code here:\n'

In [45]:
# Exercise 23: Min
"""
Find the min of nested_arr in axis 0
Your code here:
"""

'\nFind the min of nested_arr in axis 0\nYour code here:\n'

In [ ]:
# Bonus Exercise: Comprehensive Challenge
"""
Using random_arr:
1. Reshape it to a 4x5 array
2. Replace all prime numbers with -1
3. Calculate the sum of each row where values are greater than the row's mean
4. Sort the rows based on their sums
Your code here:
"""